[package]
name = "rabbit-hole-mistralrs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
mistralrs = { version = "0.7.1-alpha.1", path = "EricLBuehler/mistral.rs/mistralrs" }
tokio = "1.49.0"
